- id: chartpress
  name: chartpress --reset
  files: (Chart|chartpress|values).ya?ml
  description: Run `chartpress --reset` to clean up helm charts before committing.
  entry: chartpress --reset
  language: python
  pass_filenames: false
