os: linux
dist: bionic
language: python

stages:
  - name: test
    if: tag IS NOT present
  - name: publish
    if: tag IS present

install:
  - set -e
  - pip install --upgrade pip
  - pip install -r dev-requirements.txt
  - pip install .
  - pip freeze

before_script:
  - # Default to use helm3
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

script:
  # This is a workaround to an issue caused by the existence of a docker
  # registrymirror in our CI environment. Without this fix that removes the
  # mirror, chartpress fails to realize the existence of already built images
  # and rebuilds them.
  #
  # ref: https://github.com/moby/moby/issues/39120
  - |-
      echo '{"mtu": 1460}' | sudo dd of=/etc/docker/daemon.json &&
      sudo systemctl restart docker &&
      echo "Travis docker registry mirroring disabled.\n\n"
  - docker version
  - helm version --client
  - chartpress --version
  - chartpress --help
  - pytest --verbose --flake8

jobs:
  include:
    - name: Helm 2, Python 3.6
      python: 3.6
      before_script:
        # Install helm2 instead of helm3
        - curl -L https://git.io/get_helm.sh | bash
        - helm init --client-only

    - name: Helm 3, Python 3.7
      python: 3.7

    - name: Helm 3, Python 3.8
      python: 3.8

    - stage: publish
      before_script:
        - echo "Required dummy override of default 'before_script' in .travis.yml."
      script:
        - echo "Required dummy override of default 'script' in .travis.yml."
      deploy:
        provider: pypi
        user: "__token__"
        # password: set by TravisCI's environment variable PYPI_PASSWORD
        # ref: https://travis-ci.org/jupyterhub/chartpress/settings
        distributions: sdist bdist_wheel
        on:
          # Only deploy on tagged commits instead of the default of only doing it to
          # the master branch. A tag does not belong specifically to a branch, so
          # without this it would fail to deploy for tags.
          tags: true
