language: python
python:
  - 3.6
cache: pip
install:
  - pip install --upgrade pip
  - pip install pyflakes .
script:
  - chartpress --version
  - chartpress --help
  - pyflakes .
  - |
    # run chartpress on zero-to-jupyterhub
    git clone https://github.com/jupyterhub/zero-to-jupyterhub
    cd zero-to-jupyterhub
    chartpress
