language: python
python:
  - 3.6
cache: pip
install:
  - set -e
  - pip install --upgrade pip
  - pip install .
  - pip install -r dev-requirements.txt
script:
  - chartpress --version
  - chartpress --help
  - pytest --verbose --flakes
