language: python
python:
  - 3.6
cache: pip
install:
  - pip install --upgrade pip
  - pip install pyflakes .
script:
  - chartpress --version
  - chartpress --help
  - pyflakes .
  - |
    # This is a workaround to an issue caused by the existence of a docker registry
    # mirror in our CI environment. Without this fix that removes the mirror,
    # chartpress fails to realize the existence of already built images and rebuilds
    # them.
    #
    # ref: https://github.com/moby/moby/issues/39120
    echo '{"mtu": 1460}' | sudo dd of=/etc/docker/daemon.json
    sudo systemctl restart docker
  - |
    # run chartpress on zero-to-jupyterhub-k8s
    git clone https://github.com/jupyterhub/zero-to-jupyterhub-k8s
    cd zero-to-jupyterhub-k8s
    chartpress
    git --no-pager diff
  - |
    chartpress --reset
    git --no-pager diff
